Group history modify
angelRacancoj/Ing-Industrial-CUNOC pull request #4
Opened 2019-09-16 03:08 UTC by angelRacancoj

Se han creado las clases indicadas, se modificaron detalles dentro del diagrama de base de datos para acomodarse a las instrucciones en java (MODIFICACION_INSUMO -> tipo_modificacion ->ENUM())

2019-09-16 03:28 UTC, jgranadosiastic requested changes
Aplicar los cambios en todo lugar que aplique dentro de tu código.

2019-09-16 03:28 UTC, jgranadosiastic commented on Code/ProyectoIndustrial/Proyecto-ejb/src/main/java/Group/GroupI.java
> +    @Column(name = "seccion", insertable = true, nullable = false, lenght = 2)
Esos atributos de insertable, nullable y updatable no son necesarios. Eliminarlos en cada lugar donde aparece

2019-09-16 03:28 UTC, jgranadosiastic commented on Code/ProyectoIndustrial/Proyecto-ejb/src/main/java/Group/GroupI.java
> +public class GroupI {
Que significa 'GroupI'? Darle un nombre más descriptivo a la clase

2019-09-16 03:28 UTC, jgranadosiastic commented on Code/ProyectoIndustrial/Proyecto-ejb/src/main/java/Group/GroupUser.java
> +    private Integer id_group_user;
El nombre de variable debe ser en lower camel case

2019-09-16 03:28 UTC, jgranadosiastic commented on Code/ProyectoIndustrial/Proyecto-ejb/src/main/java/Modify/modifySupplie.java
> +public class modifySupplie {
La palabra en inglés para insumo es supply

2019-09-16 03:42 UTC, angelRacancoj commented
ya he realizado los cambios

2019-09-17 16:08 UTC, jgranadosiastic requested changes

2019-09-17 16:08 UTC, jgranadosiastic commented on Code/ProyectoIndustrial/Proyecto-ejb/src/main/java/Modify/modifyType.java
> +public enum modifyType {
El nombre debe estar en upper camel case, creo que es mejor el nombre de ModificationType

2019-09-17 16:08 UTC, jgranadosiastic commented on Code/ProyectoIndustrial/Proyecto-ejb/src/main/java/Modify/modifySupplie.java
> +public class modifySupplie {
La palabra en inglés para insumo es supply y el nombre debe estar en upper CamelCase

2019-09-17 16:33 UTC, angelRacancoj commented
ya he realizado los cambios en los nombres de las clases indicadas

2019-09-17 18:06 UTC, merged